name: Docker Image CI

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO: dfmichelangelo/backtestify-webapp
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          tags: ghcr.io/${{ env.REPO }}:latest
          push: true
